// Contains:

/*
	Copyright (c) 2011-2012, LoÔc Hoguin <essen@ninenines.eu>

	Permission to use, copy, modify, and/or distribute this software for any
	purpose with or without fee is hereby granted, provided that the above
	copyright notice and this permission notice appear in all copies.

	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
	OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

// and:

/*! jQuery v2.0.3 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
//@ sourceMappingURL=jquery-2.0.3.min.map
*/

// and: echat.js (from commit e66d59b92f0f94b0684f4813459016361788c641)

(function(r,l){function F(a){var b=a.length,c=d.type(a);return d.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===c||"function"!==c&&(0===b||"number"==typeof b&&0<b&&b-1 in a)}function V(a){var b=Pa[a]={};return d.each(a.match(R)||[],function(a,d){b[d]=!0}),b}function C(){Object.defineProperty(this.cache={},0,{get:function(){return{}}});this.expando=d.expando+Math.random()}function v(a,b,c){var d;if(c===l&&1===a.nodeType)if(d="data-"+b.replace(tb,"-$1").toLowerCase(),c=a.getAttribute(d),"string"==typeof c){try{c=
"true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:ub.test(c)?JSON.parse(c):c}catch(f){}D.set(a,b,c)}else c=l;return c}function L(){return!0}function N(){return!1}function P(){try{return y.activeElement}catch(a){}}function E(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function w(a,b,c){if(d.isFunction(b))return d.grep(a,function(a,d){return!!b.call(a,d,a)!==c});if(b.nodeType)return d.grep(a,function(a){return a===b!==c});if("string"==typeof b){if(vb.test(b))return d.filter(b,a,c);b=d.filter(b,
a)}return d.grep(a,function(a){return 0<=ra.call(b,a)!==c})}function B(a,b){return d.nodeName(a,"table")&&d.nodeName(1===b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function s(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function K(a){var b=wb.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function p(a,b){for(var c=a.length,d=0;c>d;d++)x.set(a[d],"globalEval",!b||x.get(b[d],"globalEval"))}
function Q(a,b){var c,e,f,g,h,k;if(1===b.nodeType){if(x.hasData(a)&&(c=x.access(a),e=x.set(b,c),k=c.events))for(f in delete e.handle,e.events={},k)for(c=0,e=k[f].length;e>c;c++)d.event.add(b,f,k[f][c]);D.hasData(a)&&(g=D.access(a),h=d.extend({},g),D.set(b,h))}}function q(a,b){var c=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return b===l||b&&d.nodeName(a,b)?d.merge([a],c):c}function Z(a,b){if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+
b.slice(1),d=b,f=Qa.length;f--;)if(b=Qa[f]+c,b in a)return b;return d}function I(a,b){return a=b||a,"none"===d.css(a,"display")||!d.contains(a.ownerDocument,a)}function G(a,b){for(var c,e,f,g=[],h=0,k=a.length;k>h;h++)e=a[h],e.style&&(g[h]=x.get(e,"olddisplay"),c=e.style.display,b?(g[h]||"none"!==c||(e.style.display=""),""===e.style.display&&I(e)&&(g[h]=x.access(e,"olddisplay",Ca(e.nodeName)))):g[h]||(f=I(e),(c&&"none"!==c||!f)&&x.set(e,"olddisplay",f?c:d.css(e,"display"))));for(h=0;k>h;h++)e=a[h],
e.style&&(b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none"));return a}function T(a,b,c){return(a=xb.exec(b))?Math.max(0,a[1]-(c||0))+(a[2]||"px"):b}function wa(a,b,c,e,f){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+aa[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+aa[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+aa[b]+"Width",!0,f))):(g+=d.css(a,"padding"+aa[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+aa[b]+
"Width",!0,f)));return g}function xa(a,b,c){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=r.getComputedStyle(a,null),h=d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g);if(0>=f||null==f){if(f=ba(a,b,g),(0>f||null==f)&&(f=a.style[b]),Da.test(f))return f;e=h&&(d.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+wa(a,b,c||(h?"border":"content"),e,g)+"px"}function Ca(a){var b=y,c=Ra[a];return c||(c=Sa(a,b),"none"!==c&&c||(ma=(ma||d("<iframe frameborder='0' width='0' height='0'/>").css("cssText",
"display:block !important")).appendTo(b.documentElement),b=(ma[0].contentWindow||ma[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),c=Sa(a,b),ma.detach()),Ra[a]=c),c}function Sa(a,b){var c=d(b.createElement(a)).appendTo(b.body),e=d.css(c[0],"display");return c.remove(),e}function Ea(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(b,d){c||yb.test(a)?e(a,d):Ea(a+"["+("object"==typeof d?b:"")+"]",d,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)Ea(a+"["+
f+"]",b[f],c,e)}function Ta(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");var e,f=0,g=b.toLowerCase().match(R)||[];if(d.isFunction(c))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||[]).push(c)}}function Ua(a,b,c,e){function f(k){var m;return g[k]=!0,d.each(a[k]||[],function(a,d){var k=d(b,c,e);return"string"!=typeof k||h||g[k]?h?!(m=k):l:(b.dataTypes.unshift(k),f(k),!1)}),m}var g={},h=a===Fa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ga(a,b){var c,
e,f=d.ajaxSettings.flatOptions||{};for(c in b)b[c]!==l&&((f[c]?a:e||(e={}))[c]=b[c]);return e&&d.extend(!0,a,e),a}function Va(){return setTimeout(function(){W=l}),W=d.now()}function Wa(a,b,c){for(var d,f=(ca[b]||[]).concat(ca["*"]),g=0,h=f.length;h>g;g++)if(d=f[g].call(c,b,a))return d}function Xa(a,b,c){var e,f=0,g=da.length,h=d.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;for(var b=W||Va(),b=Math.max(0,m.startTime+m.duration-b),c=1-(b/m.duration||0),d=0,f=m.tweens.length;f>
d;d++)m.tweens[d].run(c);return h.notifyWith(a,[m,c,b]),1>c&&f?b:(h.resolveWith(a,[m]),!1)},m=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{}},c),originalProperties:b,originalOptions:c,startTime:W||Va(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,m.opts,b,c,m.opts.specialEasing[b]||m.opts.easing);return m.tweens.push(e),e},stop:function(b){var c=0,d=b?m.tweens.length:0;if(e)return this;for(e=!0;d>c;c++)m.tweens[c].run(1);return b?h.resolveWith(a,
[m,b]):h.rejectWith(a,[m,b]),this}});c=m.props;for(zb(c,m.opts.specialEasing);g>f;f++)if(b=da[f].call(m,a,c,m.opts))return b;return d.map(c,Wa,m),d.isFunction(m.opts.start)&&m.opts.start.call(a,m),d.fx.timer(d.extend(k,{elem:a,anim:m,queue:m.opts.queue})),m.progress(m.opts.progress).done(m.opts.done,m.opts.complete).fail(m.opts.fail).always(m.opts.always)}function zb(a,b){var c,e,f,g,h;for(c in a)if(e=d.camelCase(c),f=b[e],g=a[c],d.isArray(g)&&(f=g[1],g=a[c]=g[0]),c!==e&&(a[e]=g,delete a[c]),h=d.cssHooks[e],
h&&"expand"in h)for(c in g=h.expand(g),delete a[e],g)c in a||(a[c]=g[c],b[c]=f);else b[e]=f}function O(a,b,c,d,f){return new O.prototype.init(a,b,c,d,f)}function ha(a,b){var c,d={height:a},f=0;for(b=b?1:0;4>f;f+=2-b)c=aa[f],d["margin"+c]=d["padding"+c]=a;return b&&(d.opacity=d.width=a),d}var Ya,sa,ta=typeof l,Ab=r.location,y=r.document,Za=y.documentElement,Bb=r.jQuery,Cb=r.$,ua={},va=[],$a=va.concat,Ha=va.push,ea=va.slice,ra=va.indexOf,Db=ua.toString,Ia=ua.hasOwnProperty,Eb="2.0.3".trim,d=function(a,
b){return new d.fn.init(a,b,Ya)},ya=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,R=/\S+/g,Fb=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/,ab=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Gb=/^-ms-/,Hb=/-([\da-z])/gi,Ib=function(a,b){return b.toUpperCase()},Aa=function(){y.removeEventListener("DOMContentLoaded",Aa,!1);r.removeEventListener("load",Aa,!1);d.ready()};d.fn=d.prototype={jquery:"2.0.3",constructor:d,init:function(a,b,c){var e,f;if(!a)return this;if("string"==typeof a){if(e="<"===a.charAt(0)&&">"===a.charAt(a.length-
1)&&3<=a.length?[null,a,null]:Fb.exec(a),!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:y,!0)),ab.test(e[1])&&d.isPlainObject(b))for(e in b)d.isFunction(this[e])?this[e](b[e]):this.attr(e,b[e]);return this}return f=y.getElementById(e[2]),f&&f.parentNode&&(this.length=1,this[0]=f),this.context=y,this.selector=a,this}return a.nodeType?(this.context=this[0]=a,this.length=1,this):
d.isFunction(a)?c.ready(a):(a.selector!==l&&(this.selector=a.selector,this.context=a.context),d.makeArray(a,this))},selector:"",length:0,toArray:function(){return ea.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,a},each:function(a,b){return d.each(this,a,b)},ready:function(a){return d.ready.promise().done(a),this},slice:function(){return this.pushStack(ea.apply(this,
arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&b>a?[this[a]]:[])},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Ha,sort:[].sort,splice:[].splice};d.fn.init.prototype=d.fn;d.extend=d.fn.extend=function(){var a,b,c,e,f,g,h=arguments[0]||{},k=1,m=arguments.length,J=!1;"boolean"==
typeof h&&(J=h,h=arguments[1]||{},k=2);"object"==typeof h||d.isFunction(h)||(h={});for(m===k&&(h=this,--k);m>k;k++)if(null!=(a=arguments[k]))for(b in a)c=h[b],e=a[b],h!==e&&(J&&e&&(d.isPlainObject(e)||(f=d.isArray(e)))?(f?(f=!1,g=c&&d.isArray(c)?c:[]):g=c&&d.isPlainObject(c)?c:{},h[b]=d.extend(J,g,e)):e!==l&&(h[b]=e));return h};d.extend({expando:"jQuery"+("2.0.3"+Math.random()).replace(/\D/g,""),noConflict:function(a){return r.$===d&&(r.$=Cb),a&&r.jQuery===d&&(r.jQuery=Bb),d},isReady:!1,readyWait:1,
holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||(sa.resolveWith(y,[d]),d.fn.trigger&&d(y).trigger("ready").off("ready")))},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?ua[Db.call(a)]||
"object":typeof a},isPlainObject:function(a){if("object"!==d.type(a)||a.nodeType||d.isWindow(a))return!1;try{if(a.constructor&&!Ia.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,b,c){if(!a||"string"!=typeof a)return null;"boolean"==typeof b&&(c=b,b=!1);b=b||y;var e=ab.exec(a);c=!c&&[];return e?[b.createElement(e[1])]:(e=d.buildFragment([a],b,c),c&&
d(c).remove(),d.merge([],e.childNodes))},parseJSON:JSON.parse,parseXML:function(a){var b,c;if(!a||"string"!=typeof a)return null;try{c=new DOMParser,b=c.parseFromString(a,"text/xml")}catch(e){b=l}return(!b||b.getElementsByTagName("parsererror").length)&&d.error("Invalid XML: "+a),b},noop:function(){},globalEval:function(a){var b,c=eval;(a=d.trim(a))&&(1===a.indexOf("use strict")?(b=y.createElement("script"),b.text=a,y.head.appendChild(b).parentNode.removeChild(b)):c(a))},camelCase:function(a){return a.replace(Gb,
"ms-").replace(Hb,Ib)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,c){var d,f=0,g=a.length,h=F(a);if(c)if(h)for(;g>f&&(d=b.apply(a[f],c),!1!==d);f++);else for(f in a){if(d=b.apply(a[f],c),!1===d)break}else if(h)for(;g>f&&(d=b.call(a[f],f,a[f]),!1!==d);f++);else for(f in a)if(d=b.call(a[f],f,a[f]),!1===d)break;return a},trim:function(a){return null==a?"":Eb.call(a)},makeArray:function(a,b){var c=b||[];return null!=a&&(F(Object(a))?d.merge(c,
"string"==typeof a?[a]:a):Ha.call(c,a)),c},inArray:function(a,b,c){return null==b?-1:ra.call(b,a,c)},merge:function(a,b){var c=b.length,d=a.length,f=0;if("number"==typeof c)for(;c>f;f++)a[d++]=b[f];else for(;b[f]!==l;)a[d++]=b[f++];return a.length=d,a},grep:function(a,b,c){var d,f=[],g=0,h=a.length;for(c=!!c;h>g;g++)d=!!b(a[g],g),c!==d&&f.push(a[g]);return f},map:function(a,b,c){var d,f=0,g=a.length,h=[];if(F(a))for(;g>f;f++)d=b(a[f],f,c),null!=d&&(h[h.length]=d);else for(f in a)d=b(a[f],f,c),null!=
d&&(h[h.length]=d);return $a.apply([],h)},guid:1,proxy:function(a,b){var c,e,f;return"string"==typeof b&&(c=a[b],b=a,a=c),d.isFunction(a)?(e=ea.call(arguments,2),f=function(){return a.apply(b||this,e.concat(ea.call(arguments)))},f.guid=a.guid=a.guid||d.guid++,f):l},access:function(a,b,c,e,f,g,h){var k=0,m=a.length,J=null==c;if("object"===d.type(c))for(k in f=!0,c)d.access(a,b,k,c[k],!0,g,h);else if(e!==l&&(f=!0,d.isFunction(e)||(h=!0),J&&(h?(b.call(a,e),b=null):(J=b,b=function(a,b,c){return J.call(d(a),
c)})),b))for(;m>k;k++)b(a[k],c,h?e:e.call(a[k],k,b(a[k],c)));return f?a:J?b.call(a):m?b(a[0],c):g},now:Date.now,swap:function(a,b,c,d){var f,g={};for(f in b)g[f]=a.style[f],a.style[f]=b[f];c=c.apply(a,d||[]);for(f in b)a.style[f]=g[f];return c}});d.ready.promise=function(a){return sa||(sa=d.Deferred(),"complete"===y.readyState?setTimeout(d.ready):(y.addEventListener("DOMContentLoaded",Aa,!1),r.addEventListener("load",Aa,!1))),sa.promise(a)};d.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),
function(a,b){ua["[object "+b+"]"]=b.toLowerCase()});Ya=d(y);(function(a,b){function c(a,b,c,d){var e,f,g,h,k;if((b?b.ownerDocument||b:fa)!==w&&na(b),b=b||w,c=c||[],!a||"string"!=typeof a)return c;if(1!==(h=b.nodeType)&&9!==h)return[];if(F&&!d){if(e=sa.exec(a))if(g=e[1])if(9===h){if(f=b.getElementById(g),!f||!f.parentNode)return c;if(f.id===g)return c.push(f),c}else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&za(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return ia.apply(c,b.getElementsByTagName(a)),
c;if((g=e[3])&&u.getElementsByClassName&&b.getElementsByClassName)return ia.apply(c,b.getElementsByClassName(g)),c}if(u.qsa&&(!S||!S.test(a))){if(f=e=M,g=b,k=9===h&&a,1===h&&"object"!==b.nodeName.toLowerCase()){h=z(a);(e=b.getAttribute("id"))?f=e.replace(va,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=h.length;g--;)h[g]=f+p(h[g]);g=ca.test(a)&&b.parentNode||b;k=h.join(",")}if(k)try{return ia.apply(c,g.querySelectorAll(k)),c}catch(m){}finally{e||b.removeAttribute("id")}}}var n;a:{a=a.replace(V,
"$1");var l,t;f=z(a);if(!d&&1===f.length){if(n=f[0]=f[0].slice(0),2<n.length&&"ID"===(l=n[0]).type&&u.getById&&9===b.nodeType&&F&&A.relative[n[1].type]){if(b=(A.find.ID(l.matches[0].replace(ja,ka),b)||[])[0],!b){n=c;break a}a=a.slice(n.shift().value.length)}for(h=da.needsContext.test(a)?0:n.length;h--&&(l=n[h],!A.relative[e=l.type]);)if((t=A.find[e])&&(d=t(l.matches[0].replace(ja,ka),ca.test(n[0].type)&&b.parentNode||b))){if(n.splice(h,1),a=d.length&&p(n),!a){n=(ia.apply(c,d),c);break a}break}}n=
(G(a,f)(d,b,!F,c,ca.test(a)),c)}return n}function e(){function a(c,d){return b.push(c+=" ")>A.cacheLength&&delete a[b.shift()],a[c]=d}var b=[];return a}function f(a){return a[M]=!0,a}function g(a){var b=w.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)A.attrHandle[c[d]]=b}function k(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||U)-(~a.sourceIndex||U);if(d)return d;
if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function m(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function t(a){return f(function(b){return b=+b,f(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function n(){}function z(a,b){var d,e,f,g,h,k,m;if(h=L[a+" "])return b?0:h.slice(0);h=a;k=[];for(m=A.preFilter;h;){d&&
!(e=Ca.exec(h))||(e&&(h=h.slice(e[0].length)||h),k.push(f=[]));d=!1;(e=ma.exec(h))&&(d=e.shift(),f.push({value:d,type:e[0].replace(V," ")}),h=h.slice(d.length));for(g in A.filter)!(e=da[g].exec(h))||m[g]&&!(e=m[g](e))||(d=e.shift(),f.push({value:d,type:g,matches:e}),h=h.slice(d.length));if(!d)break}return b?h.length:h?c.error(a):L(a,k).slice(0)}function p(a){for(var b=0,c=a.length,d="";c>b;b++)d+=a[b].value;return d}function q(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=N++;return b.first?function(b,
c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var h,k,Ja,m=X+" "+f;if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(Ja=b[M]||(b[M]={}),(k=Ja[d])&&k[0]===m){if(!0===(h=k[1])||h===I)return!0===h}else if(k=Ja[d]=[m],k[1]=a(b,c,g)||I,!0===k[1])return!0}}function s(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function x(a,b,c,d,e){for(var f,g=[],h=0,k=a.length,m=null!=
b;k>h;h++)(f=a[h])&&(!c||c(f,d,e))&&(g.push(f),m&&b.push(h));return g}function r(a,b,d,e,g,h){return e&&!e[M]&&(e=r(e)),g&&!g[M]&&(g=r(g,h)),f(function(f,h,k,m){var n,l,t=[],z=[],J=h.length,A;if(!(A=f)){A=b||"*";for(var p=k.nodeType?[k]:k,u=[],q=0,s=p.length;s>q;q++)c(A,p[q],u);A=u}A=!a||!f&&b?A:x(A,t,a,k,m);p=d?g||(f?a:J||e)?[]:h:A;if(d&&d(A,p,k,m),e)for(n=x(p,z),e(n,[],k,m),k=n.length;k--;)(l=n[k])&&(p[z[k]]=!(A[z[k]]=l));if(f){if(g||a){if(g){n=[];for(k=p.length;k--;)(l=p[k])&&n.push(A[k]=l);g(null,
p=[],n,m)}for(k=p.length;k--;)(l=p[k])&&-1<(n=g?oa.call(f,l):t[k])&&(f[n]=!(h[n]=l))}}else p=x(p===h?p.splice(J,p.length):p),g?g(null,h,p,m):ia.apply(h,p)})}function Q(a){var b,c,d,e=a.length,f=A.relative[a[0].type];c=f||A.relative[" "];for(var g=f?1:0,h=q(function(a){return a===b},c,!0),k=q(function(a){return-1<oa.call(b,a)},c,!0),m=[function(a,c,d){return!f&&(d||c!==K)||((b=c).nodeType?h(a,c,d):k(a,c,d))}];e>g;g++)if(c=A.relative[a[g].type])m=[q(s(m),c)];else{if(c=A.filter[a[g].type].apply(null,
a[g].matches),c[M]){for(d=++g;e>d&&!A.relative[a[d].type];d++);return r(1<g&&s(m),1<g&&p(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(V,"$1"),c,d>g&&Q(a.slice(g,d)),e>d&&Q(a=a.slice(d)),e>d&&p(a))}m.push(c)}return s(m)}function y(a,b){var d=0,e=0<b.length,g=0<a.length,h=function(f,h,k,m,n){var l,t,p=[],z=0,J="0",u=f&&[],q=null!=n,s=K,Ka=f||g&&A.find.TAG("*",n&&h.parentNode||h),r=X+=null==s?1:Math.random()||0.1;for(q&&(K=h!==w&&h,I=d);null!=(n=Ka[J]);J++){if(g&&n){for(l=0;t=a[l++];)if(t(n,
h,k)){m.push(n);break}q&&(X=r,I=++d)}e&&((n=!t&&n)&&z--,f&&u.push(n))}if(z+=J,e&&J!==z){for(l=0;t=b[l++];)t(u,p,h,k);if(f){if(0<z)for(;J--;)u[J]||p[J]||(p[J]=ea.call(m));p=x(p)}ia.apply(m,p);q&&!f&&0<p.length&&1<z+b.length&&c.uniqueSort(m)}return q&&(X=r,K=s),u};return e?f(h):h}var B,u,I,A,E,Z,G,K,v,na,w,Y,F,S,C,D,za,M="sizzle"+-new Date,fa=a.document,X=0,N=0,T=e(),L=e(),O=e(),H=!1,R=function(a,b){return a===b?(H=!0,0):0},P=typeof b,U=-2147483648,aa={}.hasOwnProperty,la=[],ea=la.pop,ga=la.push,ia=
la.push,wa=la.slice,oa=la.indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(this[b]===a)return b;return-1},xa="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),ba="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+xa+")|)|)[\\x20\\t\\r\\n\\f]*\\]",W=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+ba.replace(3,8)+")*)|.*)\\)|)",V=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$",
"g"),Ca=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ma=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ca=/[\x20\t\r\n\f]*[+~]/,pa=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*)[\\x20\\t\\r\\n\\f]*\\]","g"),qa=RegExp(W),ra=RegExp("^"+xa+"$"),da={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+ba),PSEUDO:RegExp("^"+W),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},ha=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ta=/^(?:input|select|textarea|button)$/i,ua=/^h\d$/i,va=/'|\\/g,ja=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)",
"ig"),ka=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(55296|a>>10,56320|1023&a)};try{ia.apply(la=wa.call(fa.childNodes),fa.childNodes),la[fa.childNodes.length].nodeType}catch(ya){ia={apply:la.length?function(a,b){ga.apply(a,wa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}Z=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};u=c.support={};na=c.setDocument=function(a){var c=
a?a.ownerDocument||a:fa;a=c.defaultView;return c!==w&&9===c.nodeType&&c.documentElement?(w=c,Y=c.documentElement,F=!Z(c),a&&a.attachEvent&&a!==a.top&&a.attachEvent("onbeforeunload",function(){na()}),u.attributes=g(function(a){return a.className="i",!a.getAttribute("className")}),u.getElementsByTagName=g(function(a){return a.appendChild(c.createComment("")),!a.getElementsByTagName("*").length}),u.getElementsByClassName=g(function(a){return a.innerHTML="<div class='a'></div><div class='a i'></div>",
a.firstChild.className="i",2===a.getElementsByClassName("i").length}),u.getById=g(function(a){return Y.appendChild(a).id=M,!c.getElementsByName||!c.getElementsByName(M).length}),u.getById?(A.find.ID=function(a,b){if(typeof b.getElementById!==P&&F){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},A.filter.ID=function(a){var b=a.replace(ja,ka);return function(a){return a.getAttribute("id")===b}}):(delete A.find.ID,A.filter.ID=function(a){var b=a.replace(ja,ka);return function(a){return(a=typeof a.getAttributeNode!==
P&&a.getAttributeNode("id"))&&a.value===b}}),A.find.TAG=u.getElementsByTagName?function(a,c){return typeof c.getElementsByTagName!==P?c.getElementsByTagName(a):b}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f},A.find.CLASS=u.getElementsByClassName&&function(a,c){return typeof c.getElementsByClassName!==P&&F?c.getElementsByClassName(a):b},C=[],S=[],(u.qsa=ha.test(c.querySelectorAll))&&(g(function(a){a.innerHTML="<select><option selected=''></option></select>";
a.querySelectorAll("[selected]").length||S.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||S.push(":checked")}),g(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("t","");a.querySelectorAll("[t^='']").length&&S.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll(":enabled").length||
S.push(":enabled",":disabled");a.querySelectorAll("*,:x");S.push(",.*:")})),(u.matchesSelector=ha.test(D=Y.webkitMatchesSelector||Y.mozMatchesSelector||Y.oMatchesSelector||Y.msMatchesSelector))&&g(function(a){u.disconnectedMatch=D.call(a,"div");D.call(a,"[s!='']:x");C.push("!=",W)}),S=S.length&&RegExp(S.join("|")),C=C.length&&RegExp(C.join("|")),za=ha.test(Y.contains)||Y.compareDocumentPosition?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||1!==d.nodeType||
!(c.contains?c.contains(d):a.compareDocumentPosition&&16&a.compareDocumentPosition(d)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},R=Y.compareDocumentPosition?function(a,b){if(a===b)return H=!0,0;var d=b.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(b);return d?1&d||!u.sortDetached&&b.compareDocumentPosition(a)===d?a===c||za(fa,a)?-1:b===c||za(fa,b)?1:v?oa.call(v,a)-oa.call(v,b):0:4&d?-1:1:a.compareDocumentPosition?-1:1}:function(a,b){var d,
e=0;d=a.parentNode;var f=b.parentNode,g=[a],h=[b];if(a===b)return H=!0,0;if(!d||!f)return a===c?-1:b===c?1:d?-1:f?1:v?oa.call(v,a)-oa.call(v,b):0;if(d===f)return k(a,b);for(d=a;d=d.parentNode;)g.unshift(d);for(d=b;d=d.parentNode;)h.unshift(d);for(;g[e]===h[e];)e++;return e?k(g[e],h[e]):g[e]===fa?-1:h[e]===fa?1:0},c):w};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){if((a.ownerDocument||a)!==w&&na(a),b=b.replace(pa,"='$1']"),u.matchesSelector&&F&&!(C&&C.test(b)||S&&
S.test(b)))try{var d=D.call(a,b);if(d||u.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<c(b,w,null,[a]).length};c.contains=function(a,b){return(a.ownerDocument||a)!==w&&na(a),za(a,b)};c.attr=function(a,c){(a.ownerDocument||a)!==w&&na(a);var d=A.attrHandle[c.toLowerCase()],d=d&&aa.call(A.attrHandle,c.toLowerCase())?d(a,c,!F):b;return d===b?u.attributes||!F?a.getAttribute(c):(d=a.getAttributeNode(c))&&d.specified?d.value:null:d};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+
a);};c.uniqueSort=function(a){var b,c=[],d=0,e=0;if(H=!u.detectDuplicates,v=!u.sortStable&&a.slice(0),a.sort(R),H){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}return a};E=c.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=E(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=E(b);return c};A=c.selectors={cacheLength:50,createPseudo:f,match:da,
attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=a[1].replace(ja,ka),a[3]=(a[4]||a[5]||"").replace(ja,ka),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]),
a},PSEUDO:function(a){var c,d=!a[5]&&a[2];return da.CHILD.test(a[0])?null:(a[3]&&a[4]!==b?a[2]=a[4]:d&&qa.test(d)&&(c=z(d,!0))&&(c=d.indexOf(")",d.length-c)-d.length)&&(a[0]=a[0].slice(0,c),a[2]=d.slice(0,c)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ja,ka).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=T[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&T(a,function(a){return b.test("string"==
typeof a.className&&a.className||typeof a.getAttribute!==P&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(e){e=c.attr(e,a);return null==e?"!="===b:b?(e+="","="===b?e===d:"!="===b?e!==d:"^="===b?d&&0===e.indexOf(d):"*="===b?d&&-1<e.indexOf(d):"$="===b?d&&e.slice(-d.length)===d:"~="===b?-1<(" "+e+" ").indexOf(d):"|="===b?e===d||e.slice(0,d.length+1)===d+"-":!1):!0}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?
function(a){return!!a.parentNode}:function(b,c,k){var m,n,l,t,p;c=f!==g?"nextSibling":"previousSibling";var z=b.parentNode,J=h&&b.nodeName.toLowerCase();k=!k&&!h;if(z){if(f){for(;c;){for(n=b;n=n[c];)if(h?n.nodeName.toLowerCase()===J:1===n.nodeType)return!1;p=c="only"===a&&!p&&"nextSibling"}return!0}if(p=[g?z.firstChild:z.lastChild],g&&k)for(k=z[M]||(z[M]={}),m=k[a]||[],t=m[0]===X&&m[1],l=m[0]===X&&m[2],n=t&&z.childNodes[t];n=++t&&n&&n[c]||(l=t=0)||p.pop();){if(1===n.nodeType&&++l&&n===b){k[a]=[X,
t,l];break}}else if(k&&(m=(b[M]||(b[M]={}))[a])&&m[0]===X)l=m[1];else for(;(n=++t&&n&&n[c]||(l=t=0)||p.pop())&&((h?n.nodeName.toLowerCase()!==J:1!==n.nodeType)||!++l||(k&&((n[M]||(n[M]={}))[a]=[X,l]),n!==b)););return l-=e,l===d||0===l%d&&0<=l/d}}},PSEUDO:function(a,b){var d,e=A.pseudos[a]||A.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return e[M]?e(b):1<e.length?(d=[a,a,"",b],A.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var d,f=e(a,b),g=f.length;g--;)d=oa.call(a,
f[g]),a[d]=!(c[d]=f[g])}):function(a){return e(a,0,d)}):e}},pseudos:{not:f(function(a){var b=[],c=[],d=G(a.replace(V,"$1"));return d[M]?f(function(a,b,c,e){var f;c=d(a,null,e,[]);for(e=a.length;e--;)(f=c[e])&&(a[e]=!(b[e]=f))}):function(a,e,f){return b[0]=a,d(b,null,f,c),!c.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){return function(b){return-1<(b.textContent||b.innerText||E(b)).indexOf(a)}}),lang:f(function(a){return ra.test(a||"")||c.error("unsupported lang: "+
a),a=a.replace(ja,ka).toLowerCase(),function(b){var c;do if(c=F?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===Y},focus:function(a){return a===w.activeElement&&(!w.hasFocus||w.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===
a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;return!0},parent:function(a){return!A.pseudos.empty(a)},header:function(a){return ua.test(a.nodeName)},input:function(a){return ta.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();
return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:t(function(){return[0]}),last:t(function(a,b){return[b-1]}),eq:t(function(a,b,c){return[0>c?c+b:c]}),even:t(function(a,b){for(var c=0;b>c;c+=2)a.push(c);return a}),odd:t(function(a,b){for(var c=1;b>c;c+=2)a.push(c);return a}),lt:t(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:t(function(a,
b,c){for(c=0>c?c+b:c;b>++c;)a.push(c);return a})}};A.pseudos.nth=A.pseudos.eq;for(B in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})A.pseudos[B]=m(B);for(B in{submit:!0,reset:!0})A.pseudos[B]=l(B);n.prototype=A.filters=A.pseudos;A.setFilters=new n;G=c.compile=function(a,b){var c,d=[],e=[],f=O[a+" "];if(!f){b||(b=z(a));for(c=b.length;c--;)f=Q(b[c]),f[M]?d.push(f):e.push(f);f=O(a,y(e,d))}return f};u.sortStable=M.split("").sort(R).join("")===M;u.detectDuplicates=H;na();u.sortDetached=g(function(a){return 1&
a.compareDocumentPosition(w.createElement("div"))});g(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||h("type|href|height|width",function(a,c,d){return d?b:a.getAttribute(c,"type"===c.toLowerCase()?1:2)});u.attributes&&g(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",""),""===a.firstChild.getAttribute("value")})||h("value",function(a,c,d){return d||"input"!==a.nodeName.toLowerCase()?b:a.defaultValue});g(function(a){return null==
a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,c,d){var e;return d?b:(e=a.getAttributeNode(c))&&e.specified?e.value:!0===a[c]?c.toLowerCase():null});d.find=c;d.expr=c.selectors;d.expr[":"]=d.expr.pseudos;d.unique=c.uniqueSort;d.text=c.getText;d.isXMLDoc=c.isXML;d.contains=c.contains})(r);var Pa={};d.Callbacks=function(a){a="string"==typeof a?Pa[a]||V(a):d.extend({},a);var b,c,e,
f,g,h,k=[],m=!a.once&&[],p=function(d){b=a.memory&&d;c=!0;h=f||0;f=0;g=k.length;for(e=!0;k&&g>h;h++)if(!1===k[h].apply(d[0],d[1])&&a.stopOnFalse){b=!1;break}e=!1;k&&(m?m.length&&p(m.shift()):b?k=[]:t.disable())},t={add:function(){if(k){var c=k.length;(function Ka(b){d.each(b,function(b,c){var e=d.type(c);"function"===e?a.unique&&t.has(c)||k.push(c):c&&c.length&&"string"!==e&&Ka(c)})})(arguments);e?g=k.length:b&&(f=c,p(b))}return this},remove:function(){return k&&d.each(arguments,function(a,b){for(var c;-1<
(c=d.inArray(b,k,c));)k.splice(c,1),e&&(g>=c&&g--,h>=c&&h--)}),this},has:function(a){return a?-1<d.inArray(a,k):!(!k||!k.length)},empty:function(){return k=[],g=0,this},disable:function(){return k=m=b=l,this},disabled:function(){return!k},lock:function(){return m=l,b||t.disable(),this},locked:function(){return!m},fireWith:function(a,b){return!k||c&&!m||(b=b||[],b=[a,b.slice?b.slice():b],e?m.push(b):p(b)),this},fire:function(){return t.fireWith(this,arguments),this},fired:function(){return!!c}};return t};
d.extend({Deferred:function(a){var b=[["resolve","done",d.Callbacks("once memory"),"resolved"],["reject","fail",d.Callbacks("once memory"),"rejected"],["notify","progress",d.Callbacks("memory")]],c="pending",e={state:function(){return c},always:function(){return f.done(arguments).fail(arguments),this},then:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,m){var l=m[0],t=d.isFunction(a[b])&&a[b];f[m[1]](function(){var a=t&&t.apply(this,arguments);a&&d.isFunction(a.promise)?
a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[l+"With"](this===e?c.promise():this,t?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?d.extend(a,e):e}},f={};return e.pipe=e.then,d.each(b,function(a,d){var k=d[2],m=d[3];e[d[1]]=k.add;m&&k.add(function(){c=m},b[1^a][2].disable,b[2][2].lock);f[d[0]]=function(){return f[d[0]+"With"](this===f?e:this,arguments),this};f[d[0]+"With"]=k.fireWith}),e.promise(f),a&&a.call(f,f),f},when:function(a){var b=0,c=ea.call(arguments),
e=c.length,f=1!==e||a&&d.isFunction(a.promise)?e:0,g=1===f?a:d.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?ea.call(arguments):d;c===k?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},k,m,l;if(1<e)for(k=Array(e),m=Array(e),l=Array(e);e>b;b++)c[b]&&d.isFunction(c[b].promise)?c[b].promise().done(h(b,l,c)).fail(g.reject).progress(h(b,m,k)):--f;return f||g.resolveWith(l,c),g.promise()}});d.support=function(a){var b=y.createElement("input"),c=y.createDocumentFragment(),
e=y.createElement("div"),f=y.createElement("select"),g=f.appendChild(y.createElement("option"));return b.type?(b.type="checkbox",a.checkOn=""!==b.value,a.optSelected=g.selected,a.reliableMarginRight=!0,a.boxSizingReliable=!0,a.pixelPosition=!1,b.checked=!0,a.noCloneChecked=b.cloneNode(!0).checked,f.disabled=!0,a.optDisabled=!g.disabled,b=y.createElement("input"),b.value="t",b.type="radio",a.radioValue="t"===b.value,b.setAttribute("checked","t"),b.setAttribute("name","t"),c.appendChild(b),a.checkClone=
c.cloneNode(!0).cloneNode(!0).lastChild.checked,a.focusinBubbles="onfocusin"in r,e.style.backgroundClip="content-box",e.cloneNode(!0).style.backgroundClip="",a.clearCloneStyle="content-box"===e.style.backgroundClip,d(function(){var b,c,f=y.getElementsByTagName("body")[0];f&&(b=y.createElement("div"),b.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px",f.appendChild(b).appendChild(e),e.innerHTML="",e.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%",
d.swap(f,null!=f.style.zoom?{zoom:1}:{},function(){a.boxSizing=4===e.offsetWidth}),r.getComputedStyle&&(a.pixelPosition="1%"!==(r.getComputedStyle(e,null)||{}).top,a.boxSizingReliable="4px"===(r.getComputedStyle(e,null)||{width:"4px"}).width,c=e.appendChild(y.createElement("div")),c.style.cssText=e.style.cssText="padding:0;margin:0;border:0;display:block;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box",c.style.marginRight=c.style.width="0",e.style.width="1px",a.reliableMarginRight=
!parseFloat((r.getComputedStyle(c,null)||{}).marginRight)),f.removeChild(b))}),a):a}({});var D,x,ub=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,tb=/([A-Z])/g;C.uid=1;C.accepts=function(a){return a.nodeType?1===a.nodeType||9===a.nodeType:!0};C.prototype={key:function(a){if(!C.accepts(a))return 0;var b={},c=a[this.expando];if(!c){c=C.uid++;try{b[this.expando]={value:c},Object.defineProperties(a,b)}catch(e){b[this.expando]=c,d.extend(a,b)}}return this.cache[c]||(this.cache[c]={}),c},set:function(a,b,c){var e;a=this.key(a);
var f=this.cache[a];if("string"==typeof b)f[b]=c;else if(d.isEmptyObject(f))d.extend(this.cache[a],b);else for(e in b)f[e]=b[e];return f},get:function(a,b){var c=this.cache[this.key(a)];return b===l?c:c[b]},access:function(a,b,c){var e;return b===l||b&&"string"==typeof b&&c===l?(e=this.get(a,b),e!==l?e:this.get(a,d.camelCase(b))):(this.set(a,b,c),c!==l?c:b)},remove:function(a,b){var c,e,f=this.key(a),g=this.cache[f];if(b===l)this.cache[f]={};else for(d.isArray(b)?e=b.concat(b.map(d.camelCase)):(c=
d.camelCase(b),b in g?e=[b,c]:(e=c,e=e in g?[e]:e.match(R)||[])),c=e.length;c--;)delete g[e[c]]},hasData:function(a){return!d.isEmptyObject(this.cache[a[this.expando]]||{})},discard:function(a){a[this.expando]&&delete this.cache[a[this.expando]]}};D=new C;x=new C;d.extend({acceptData:C.accepts,hasData:function(a){return D.hasData(a)||x.hasData(a)},data:function(a,b,c){return D.access(a,b,c)},removeData:function(a,b){D.remove(a,b)},_data:function(a,b,c){return x.access(a,b,c)},_removeData:function(a,
b){x.remove(a,b)}});d.fn.extend({data:function(a,b){var c,e,f=this[0],g=0,h=null;if(a===l){if(this.length&&(h=D.get(f),1===f.nodeType&&!x.get(f,"hasDataAttrs"))){for(c=f.attributes;c.length>g;g++)e=c[g].name,0===e.indexOf("data-")&&(e=d.camelCase(e.slice(5)),v(f,e,h[e]));x.set(f,"hasDataAttrs",!0)}return h}return"object"==typeof a?this.each(function(){D.set(this,a)}):d.access(this,function(b){var c,e=d.camelCase(a);if(f&&b===l){if((c=D.get(f,a),c!==l)||(c=D.get(f,e),c!==l)||(c=v(f,e,l),c!==l))return c}else this.each(function(){var c=
D.get(this,e);D.set(this,e,b);-1!==a.indexOf("-")&&c!==l&&D.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){D.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;return a?(b=(b||"fx")+"queue",e=x.get(a,b),c&&(!e||d.isArray(c)?e=x.access(a,b,d.makeArray(c)):e.push(c)),e||[]):l},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&
("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return x.get(a,c)||x.access(a,c,{empty:d.Callbacks("once memory").add(function(){x.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),c>arguments.length?d.queue(this[0],a):b===l?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,
a)})},delay:function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,d){var f=setTimeout(b,a);d.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=l);for(a=a||"fx";h--;)(c=x.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(k));return k(),f.promise(b)}});var bb,La=/[\t\r\n\f]/g,Jb=/\r/g,Kb=/^(?:input|select|textarea|button)$/i;
d.fn.extend({attr:function(a,b){return d.access(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})},prop:function(a,b){return d.access(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})},addClass:function(a){var b,c,e,f,g,h=0,k=this.length;b="string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,this.className))});if(b)for(b=
(a||"").match(R)||[];k>h;h++)if(c=this[h],e=1===c.nodeType&&(c.className?(" "+c.className+" ").replace(La," "):" ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");c.className=d.trim(e)}return this},removeClass:function(a){var b,c,e,f,g,h=0,k=this.length;b=0===arguments.length||"string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(R)||[];k>h;h++)if(c=this[h],e=1===c.nodeType&&(c.className?(" "+c.className+
" ").replace(La," "):"")){for(g=0;f=b[g++];)for(;0<=e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");c.className=a?d.trim(e):""}return this},toggleClass:function(a,b){var c=typeof a;return"boolean"==typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,this.className,b),b)}):this.each(function(){if("string"===c)for(var b,f=0,g=d(this),h=a.match(R)||[];b=h[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else(c===ta||
"boolean"===c)&&(this.className&&x.set(this,"__className__",this.className),this.className=this.className||!1===a?"":x.get(this,"__className__")||"")})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;c>b;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(La," ").indexOf(a))return!0;return!1},val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(c){var f;1===this.nodeType&&(f=e?a.call(this,c,d(this).val()):a,null==f?f="":"number"==
typeof f?f+="":d.isArray(f)&&(f=d.map(f,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&b.set(this,f,"value")!==l||(this.value=f))});if(f)return b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&(c=b.get(f,"value"))!==l?c:(c=f.value,"string"==typeof c?c.replace(Jb,""):null==c?"":c)}});d.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,
c=a.options,e=a.selectedIndex,f="select-one"===a.type||0>e,g=f?null:[],h=f?e+1:c.length,k=0>e?h:f?e:0;h>k;k++)if(b=c[k],!(!b.selected&&k!==e||(d.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&d.nodeName(b.parentNode,"optgroup"))){if(a=d(b).val(),f)return a;g.push(a)}return g},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),h=f.length;h--;)e=f[h],(e.selected=0<=d.inArray(d(e).val(),g))&&(c=!0);return c||(a.selectedIndex=-1),g}}},attr:function(a,
b,c){var e,f,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return typeof a.getAttribute===ta?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||(b=b.toLowerCase(),e=d.attrHooks[b]||(d.expr.match.bool.test(b)?bb:void 0)),c===l?e&&"get"in e&&null!==(f=e.get(a,b))?f:(f=d.find.attr(a,b),null==f?l:f):null!==c?e&&"set"in e&&(f=e.set(a,c,b))!==l?f:(a.setAttribute(b,c+""),c):(d.removeAttr(a,b),l))},removeAttr:function(a,b){var c,e,f=0,g=b&&b.match(R);if(g&&1===a.nodeType)for(;c=g[f++];)e=d.propFix[c]||c,d.expr.match.bool.test(c)&&
(a[e]=!1),a.removeAttribute(c)},attrHooks:{type:{set:function(a,b){if(!d.support.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,c){var e,f,g,h=a.nodeType;if(a&&3!==h&&8!==h&&2!==h)return g=1!==h||!d.isXMLDoc(a),g&&(b=d.propFix[b]||b,f=d.propHooks[b]),c!==l?f&&"set"in f&&(e=f.set(a,c,b))!==l?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){return a.hasAttribute("tabindex")||
Kb.test(a.nodeName)||a.href?a.tabIndex:-1}}}});bb={set:function(a,b,c){return!1===b?d.removeAttr(a,c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=d.expr.attrHandle[b]||d.find.attr;d.expr.attrHandle[b]=function(a,b,g){var h=d.expr.attrHandle[b];a=g?l:(d.expr.attrHandle[b]=l)!=c(a,b,g)?b.toLowerCase():null;return d.expr.attrHandle[b]=h,a}});d.support.optSelected||(d.propHooks.selected={get:function(a){a=a.parentNode;return a&&(a.parentNode&&a.parentNode.selectedIndex),
null}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){return d.isArray(b)?a.checked=0<=d.inArray(d(a).val(),b):l}};d.support.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Lb=/^key/,Mb=/^(?:mouse|contextmenu)|click/,cb=/^(?:focusinfocus|focusoutblur)$/,
db=/^([^.]*)(?:\.(.+)|)$/;d.event={global:{},add:function(a,b,c,e,f){var g,h,k,m,p,t,n,z,q,s;if(p=x.get(a)){c.handler&&(g=c,c=g.handler,f=g.selector);c.guid||(c.guid=d.guid++);(m=p.events)||(m=p.events={});(h=p.handle)||(h=p.handle=function(a){return typeof d===ta||a&&d.event.triggered===a.type?l:d.event.dispatch.apply(h.elem,arguments)},h.elem=a);b=(b||"").match(R)||[""];for(p=b.length;p--;)k=db.exec(b[p])||[],q=s=k[1],k=(k[2]||"").split(".").sort(),q&&(n=d.event.special[q]||{},q=(f?n.delegateType:
n.bindType)||q,n=d.event.special[q]||{},t=d.extend({type:q,origType:s,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:k.join(".")},g),(z=m[q])||(z=m[q]=[],z.delegateCount=0,n.setup&&!1!==n.setup.call(a,e,k,h)||a.addEventListener&&a.addEventListener(q,h,!1)),n.add&&(n.add.call(a,t),t.handler.guid||(t.handler.guid=c.guid)),f?z.splice(z.delegateCount++,0,t):z.push(t),d.event.global[q]=!0);a=null}},remove:function(a,b,c,e,f){var g,h,k,m,l,p,n,z,q,s,
r,Q=x.hasData(a)&&x.get(a);if(Q&&(m=Q.events)){b=(b||"").match(R)||[""];for(l=b.length;l--;)if(k=db.exec(b[l])||[],q=r=k[1],s=(k[2]||"").split(".").sort(),q){n=d.event.special[q]||{};q=(e?n.delegateType:n.bindType)||q;z=m[q]||[];k=k[2]&&RegExp("(^|\\.)"+s.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=z.length;g--;)p=z[g],!f&&r!==p.origType||c&&c.guid!==p.guid||k&&!k.test(p.namespace)||e&&e!==p.selector&&("**"!==e||!p.selector)||(z.splice(g,1),p.selector&&z.delegateCount--,n.remove&&n.remove.call(a,p));
h&&!z.length&&(n.teardown&&!1!==n.teardown.call(a,s,Q.handle)||d.removeEvent(a,q,Q.handle),delete m[q])}else for(q in m)d.event.remove(a,q+b[l],c,e,!0);d.isEmptyObject(m)&&(delete Q.handle,x.remove(a,"events"))}},trigger:function(a,b,c,e){var f,g,h,k,m,p,t,n=[c||y],q=Ia.call(a,"type")?a.type:a;f=Ia.call(a,"namespace")?a.namespace.split("."):[];if(g=h=c=c||y,3!==c.nodeType&&8!==c.nodeType&&!cb.test(q+d.event.triggered)&&(0<=q.indexOf(".")&&(f=q.split("."),q=f.shift(),f.sort()),m=0>q.indexOf(":")&&
"on"+q,a=a[d.expando]?a:new d.Event(q,"object"==typeof a&&a),a.isTrigger=e?2:3,a.namespace=f.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+f.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=l,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),t=d.event.special[q]||{},e||!t.trigger||!1!==t.trigger.apply(c,b))){if(!e&&!t.noBubble&&!d.isWindow(c)){k=t.delegateType||q;for(cb.test(k+q)||(g=g.parentNode);g;g=g.parentNode)n.push(g),h=g;h===(c.ownerDocument||y)&&n.push(h.defaultView||h.parentWindow||
r)}for(f=0;(g=n[f++])&&!a.isPropagationStopped();)a.type=1<f?k:t.bindType||q,(p=(x.get(g,"events")||{})[a.type]&&x.get(g,"handle"))&&p.apply(g,b),(p=m&&g[m])&&d.acceptData(g)&&p.apply&&!1===p.apply(g,b)&&a.preventDefault();return a.type=q,e||a.isDefaultPrevented()||t._default&&!1!==t._default.apply(n.pop(),b)||!d.acceptData(c)||m&&d.isFunction(c[q])&&!d.isWindow(c)&&(h=c[m],h&&(c[m]=null),d.event.triggered=q,c[q](),d.event.triggered=l,h&&(c[m]=h)),a.result}},dispatch:function(a){a=d.event.fix(a);
var b,c,e,f,g,h=[],k=ea.call(arguments);b=(x.get(this,"events")||{})[a.type]||[];var m=d.event.special[a.type]||{};if(k[0]=a,a.delegateTarget=this,!m.preDispatch||!1!==m.preDispatch.call(this,a)){h=d.event.handlers.call(this,a,b);for(b=0;(f=h[b++])&&!a.isPropagationStopped();)for(a.currentTarget=f.elem,c=0;(g=f.handlers[c++])&&!a.isImmediatePropagationStopped();)a.namespace_re&&!a.namespace_re.test(g.namespace)||(a.handleObj=g,a.data=g.data,e=((d.event.special[g.origType]||{}).handle||g.handler).apply(f.elem,
k),e===l||!1!==(a.result=e)||(a.preventDefault(),a.stopPropagation()));return m.postDispatch&&m.postDispatch.call(this,a),a.result}},handlers:function(a,b){var c,e,f,g,h=[],k=b.delegateCount,m=a.target;if(k&&m.nodeType&&(!a.button||"click"!==a.type))for(;m!==this;m=m.parentNode||this)if(!0!==m.disabled||"click"!==a.type){e=[];for(c=0;k>c;c++)g=b[c],f=g.selector+" ",e[f]===l&&(e[f]=g.needsContext?0<=d(f,this).index(m):d.find(f,this,null,[m]).length),e[f]&&e.push(g);e.length&&h.push({elem:m,handlers:e})}return b.length>
k&&h.push({elem:this,handlers:b.slice(k)}),h},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,d,f,g=b.button;return null==
a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||y,d=c.documentElement,f=c.body,a.pageX=b.clientX+(d&&d.scrollLeft||f&&f.scrollLeft||0)-(d&&d.clientLeft||f&&f.clientLeft||0),a.pageY=b.clientY+(d&&d.scrollTop||f&&f.scrollTop||0)-(d&&d.clientTop||f&&f.clientTop||0)),a.which||g===l||(a.which=1&g?1:2&g?3:4&g?2:0),a}},fix:function(a){if(a[d.expando])return a;var b,c,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=Mb.test(b)?this.mouseHooks:Lb.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):
this.props;a=new d.Event(f);for(b=e.length;b--;)c=e[b],a[c]=f[c];return a.target||(a.target=y),3===a.target.nodeType&&(a.target=a.target.parentNode),g.filter?g.filter(a,f):a},special:{load:{noBubble:!0},focus:{trigger:function(){return this!==P()&&this.focus?(this.focus(),!1):l},delegateType:"focusin"},blur:{trigger:function(){return this===P()&&this.blur?(this.blur(),!1):l},delegateType:"focusout"},click:{trigger:function(){return"checkbox"===this.type&&this.click&&d.nodeName(this,"input")?(this.click(),
!1):l},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){a.result!==l&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,c,e){a=d.extend(new d.Event,c,{type:a,isSimulated:!0,originalEvent:{}});e?d.event.trigger(a,null,b):d.event.dispatch.call(b,a);a.isDefaultPrevented()&&c.preventDefault()}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};d.Event=function(a,b){return this instanceof d.Event?(a&&a.type?(this.originalEvent=
a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||a.getPreventDefault&&a.getPreventDefault()?L:N):this.type=a,b&&d.extend(this,b),this.timeStamp=a&&a.timeStamp||d.now(),this[d.expando]=!0,l):new d.Event(a,b)};d.Event.prototype={isDefaultPrevented:N,isPropagationStopped:N,isImmediatePropagationStopped:N,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=L;a&&a.preventDefault&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=
L;a&&a.stopPropagation&&a.stopPropagation()},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=L;this.stopPropagation()}};d.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;return(!f||f!==this&&!d.contains(this,f))&&(a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b),e}}});d.support.focusinBubbles||d.each({focus:"focusin",blur:"focusout"},function(a,
b){var c=0,e=function(a){d.event.simulate(b,a.target,d.event.fix(a),!0)};d.event.special[b]={setup:function(){0===c++&&y.addEventListener(a,e,!0)},teardown:function(){0===--c&&y.removeEventListener(a,e,!0)}}});d.fn.extend({on:function(a,b,c,e,f){var g,h;if("object"==typeof a){"string"!=typeof b&&(c=c||b,b=l);for(h in a)this.on(h,b,c,a[h],f);return this}if(null==c&&null==e?(e=b,c=b=l):null==e&&("string"==typeof b?(e=c,c=l):(e=c,c=b,b=l)),!1===e)e=N;else if(!e)return this;return 1===f&&(g=e,e=function(a){return d().off(a),
g.apply(this,arguments)},e.guid=g.guid||(g.guid=d.guid++)),this.each(function(){d.event.add(this,a,e,c,b)})},one:function(a,b,c,d){return this.on(a,b,c,d,1)},off:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}return(!1===b||"function"==typeof b)&&(c=b,b=l),!1===c&&(c=N),this.each(function(){d.event.remove(this,
a,c,b)})},trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];return c?d.event.trigger(a,b,c,!0):l}});var vb=/^.[^:#\[\.,]*$/,Nb=/^(?:parents|prev(?:Until|All))/,eb=d.expr.match.needsContext,Ob={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({find:function(a){var b,c=[],e=this,f=e.length;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;f>b;b++)if(d.contains(e[b],this))return!0}));for(b=0;f>b;b++)d.find(a,
e[b],c);return c=this.pushStack(1<f?d.unique(c):c),c.selector=this.selector?this.selector+" "+a:a,c},has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;c>a;a++)if(d.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(w(this,a||[],!0))},filter:function(a){return this.pushStack(w(this,a||[],!1))},is:function(a){return!!w(this,"string"==typeof a&&eb.test(a)?d(a):a||[],!1).length},closest:function(a,b){for(var c,e=0,f=this.length,g=[],h=eb.test(a)||
"string"!=typeof a?d(a,b||this.context):0;f>e;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.unique(g):g)},index:function(a){return a?"string"==typeof a?ra.call(d(a),this[0]):ra.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){var c="string"==typeof a?d(a,b):d.makeArray(a&&a.nodeType?[a]:a),c=d.merge(this.get(),c);
return this.pushStack(d.unique(c))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return d.dir(a,"parentNode")},parentsUntil:function(a,b,c){return d.dir(a,"parentNode",c)},next:function(a){return E(a,"nextSibling")},prev:function(a){return E(a,"previousSibling")},nextAll:function(a){return d.dir(a,"nextSibling")},prevAll:function(a){return d.dir(a,"previousSibling")},
nextUntil:function(a,b,c){return d.dir(a,"nextSibling",c)},prevUntil:function(a,b,c){return d.dir(a,"previousSibling",c)},siblings:function(a){return d.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return d.sibling(a.firstChild)},contents:function(a){return a.contentDocument||d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);return"Until"!==a.slice(-5)&&(e=c),e&&"string"==typeof e&&(f=d.filter(e,f)),1<this.length&&(Ob[a]||d.unique(f),Nb.test(a)&&
f.reverse()),this.pushStack(f)}});d.extend({filter:function(a,b,c){var e=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))},dir:function(a,b,c){for(var e=[],f=c!==l;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var fb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
gb=/<([\w:]+)/,Pb=/<|&#?\w+;/,Qb=/<(?:script|style|link)/i,hb=/^(?:checkbox|radio)$/i,Rb=/checked\s*(?:[^=]|=\s*.checked.)/i,ib=/^$|\/(?:java|ecma)script/i,wb=/^true\/(.*)/,Sb=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,H={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};H.optgroup=H.option;H.tbody=H.tfoot=
H.colgroup=H.caption=H.thead;H.th=H.td;d.fn.extend({text:function(a){return d.access(this,function(a){return a===l?d.text(this):this.empty().append((this[0]&&this[0].ownerDocument||y).createTextNode(a))},null,a,arguments.length)},append:function(){return this.domManip(arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||B(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=
B(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var c,e=a?d.filter(a,this):this,f=0;null!=(c=e[f]);f++)b||1!==c.nodeType||d.cleanData(q(c)),c.parentNode&&(b&&d.contains(c.ownerDocument,c)&&p(q(c,"script")),c.parentNode.removeChild(c));
return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(q(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return d.access(this,function(a){var c=this[0]||{},e=0,f=this.length;if(a===l&&1===c.nodeType)return c.innerHTML;if("string"==typeof a&&!Qb.test(a)&&!H[(gb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(fb,"<$1></$2>");try{for(;f>e;e++)c=this[e]||
{},1===c.nodeType&&(d.cleanData(q(c,!1)),c.innerHTML=a);c=0}catch(g){}}c&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=d.map(this,function(a){return[a.nextSibling,a.parentNode]}),b=0;return this.domManip(arguments,function(c){var e=a[b++],f=a[b++];f&&(e&&e.parentNode!==f&&(e=this.nextSibling),d(this).remove(),f.insertBefore(c,e))},!0),b?this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,c){a=$a.apply([],a);var e,f,g,h,k=0,m=this.length,
l=this,p=m-1,n=a[0],z=d.isFunction(n);if(z||!(1>=m||"string"!=typeof n||d.support.checkClone)&&Rb.test(n))return this.each(function(d){var e=l.eq(d);z&&(a[0]=n.call(this,d,e.html()));e.domManip(a,b,c)});if(m&&(e=d.buildFragment(a,this[0].ownerDocument,!1,!c&&this),f=e.firstChild,1===e.childNodes.length&&(e=f),f)){f=d.map(q(e,"script"),s);for(g=f.length;m>k;k++)h=e,k!==p&&(h=d.clone(h,!0,!0),g&&d.merge(f,q(h,"script"))),b.call(this[k],h,k);if(g)for(e=f[f.length-1].ownerDocument,d.map(f,K),k=0;g>k;k++)h=
f[k],ib.test(h.type||"")&&!x.access(h,"globalEval")&&d.contains(e,h)&&(h.src?d._evalUrl(h.src):d.globalEval(h.textContent.replace(Sb,"")))}return this}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var e=[],f=d(a),g=f.length-1,h=0;g>=h;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),Ha.apply(e,a.get());return this.pushStack(e)}});d.extend({clone:function(a,b,c){var e,f,g,h,k=a.cloneNode(!0),m=
d.contains(a.ownerDocument,a);if(!(d.support.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a)))for(h=q(k),g=q(a),e=0,f=g.length;f>e;e++){var l=g[e],t=h[e],n=t.nodeName.toLowerCase();"input"===n&&hb.test(l.type)?t.checked=l.checked:("input"===n||"textarea"===n)&&(t.defaultValue=l.defaultValue)}if(b)if(c)for(g=g||q(a),h=h||q(k),e=0,f=g.length;f>e;e++)Q(g[e],h[e]);else Q(a,k);return h=q(k,"script"),0<h.length&&p(h,!m&&q(a,"script")),k},buildFragment:function(a,b,c,e){for(var f,g,h,k,m=
0,l=a.length,t=b.createDocumentFragment(),n=[];l>m;m++)if(f=a[m],f||0===f)if("object"===d.type(f))d.merge(n,f.nodeType?[f]:f);else if(Pb.test(f)){g=g||t.appendChild(b.createElement("div"));h=(gb.exec(f)||["",""])[1].toLowerCase();h=H[h]||H._default;g.innerHTML=h[1]+f.replace(fb,"<$1></$2>")+h[2];for(h=h[0];h--;)g=g.lastChild;d.merge(n,g.childNodes);g=t.firstChild;g.textContent=""}else n.push(b.createTextNode(f));t.textContent="";for(m=0;f=n[m++];)if((!e||-1===d.inArray(f,e))&&(k=d.contains(f.ownerDocument,
f),g=q(t.appendChild(f),"script"),k&&p(g),c))for(h=0;f=g[h++];)ib.test(f.type||"")&&c.push(f);return t},cleanData:function(a){for(var b,c,e,f,g,h,k=d.event.special,m=0;(c=a[m])!==l;m++){if(C.accepts(c)&&(g=c[x.expando],g&&(b=x.cache[g]))){if(e=Object.keys(b.events||{}),e.length)for(h=0;(f=e[h])!==l;h++)k[f]?d.event.remove(c,f):d.removeEvent(c,f,b.handle);x.cache[g]&&delete x.cache[g]}delete D.cache[c[D.expando]]}},_evalUrl:function(a){return d.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,
"throws":!0})}});d.fn.extend({wrapAll:function(a){var b;return d.isFunction(a)?this.each(function(b){d(this).wrapAll(a.call(this,b))}):(this[0]&&(b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)),this)},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?
c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()}});var ba,ma,Tb=/^(none|table(?!-c[ea]).+)/,jb=/^margin/,xb=RegExp("^("+ya+")(.*)$","i"),Da=RegExp("^("+ya+")(?!px)[a-z%]+$","i"),Ub=RegExp("^([+-])=("+ya+")","i"),Ra={BODY:"block"},Vb={position:"absolute",visibility:"hidden",display:"block"},
kb={letterSpacing:0,fontWeight:400},aa=["Top","Right","Bottom","Left"],Qa=["Webkit","O","Moz","ms"];d.fn.extend({css:function(a,b){return d.access(this,function(a,b,f){var g,h={},k=0;if(d.isArray(b)){f=r.getComputedStyle(a,null);for(g=b.length;g>k;k++)h[b[k]]=d.css(a,b[k],!1,f);return h}return f!==l?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)},show:function(){return G(this,!0)},hide:function(){return G(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){I(this)?
d(this).show():d(this).hide()})}});d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=ba(a,"opacity");return""===c?"1":c}}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,h,k=d.camelCase(b),m=a.style;return b=d.cssProps[k]||(d.cssProps[k]=Z(m,k)),h=d.cssHooks[b]||d.cssHooks[k],c===l?h&&"get"in h&&(f=
h.get(a,!1,e))!==l?f:m[b]:(g=typeof c,"string"===g&&(f=Ub.exec(c))&&(c=(f[1]+1)*f[2]+parseFloat(d.css(a,b)),g="number"),null==c||"number"===g&&isNaN(c)||("number"!==g||d.cssNumber[k]||(c+="px"),d.support.clearCloneStyle||""!==c||0!==b.indexOf("background")||(m[b]="inherit"),h&&"set"in h&&(c=h.set(a,c,e))===l||(m[b]=c)),l)}},css:function(a,b,c,e){var f,g,h,k=d.camelCase(b);return b=d.cssProps[k]||(d.cssProps[k]=Z(a.style,k)),h=d.cssHooks[b]||d.cssHooks[k],h&&"get"in h&&(f=h.get(a,!0,c)),f===l&&(f=
ba(a,b,e)),"normal"===f&&b in kb&&(f=kb[b]),""===c||c?(g=parseFloat(f),!0===c||d.isNumeric(g)?g||0:f):f}});ba=function(a,b,c){var e,f,g,h=(c=c||r.getComputedStyle(a,null))?c.getPropertyValue(b)||c[b]:l,k=a.style;return c&&(""!==h||d.contains(a.ownerDocument,a)||(h=d.style(a,b)),Da.test(h)&&jb.test(b)&&(e=k.width,f=k.minWidth,g=k.maxWidth,k.minWidth=k.maxWidth=k.width=h,h=c.width,k.width=e,k.minWidth=f,k.maxWidth=g)),h};d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){return e?
0===a.offsetWidth&&Tb.test(d.css(a,"display"))?d.swap(a,Vb,function(){return xa(a,b,f)}):xa(a,b,f):l},set:function(a,e,f){var g=f&&r.getComputedStyle(a,null);return T(a,e,f?wa(a,b,f,d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g),g):0)}}});d(function(){d.support.reliableMarginRight||(d.cssHooks.marginRight={get:function(a,b){return b?d.swap(a,{display:"inline-block"},ba,[a,"marginRight"]):l}});!d.support.pixelPosition&&d.fn.position&&d.each(["top","left"],function(a,b){d.cssHooks[b]=
{get:function(a,e){return e?(e=ba(a,b),Da.test(e)?d(a).position()[b]+"px":e):l}}})});d.expr&&d.expr.filters&&(d.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight},d.expr.filters.visible=function(a){return!d.expr.filters.hidden(a)});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"==typeof c?c.split(" "):[c];4>d;d++)f[a+aa[d]+b]=c[d]||c[d-2]||c[0];return f}};jb.test(a)||(d.cssHooks[a+b].set=T)});var Wb=
/%20/g,yb=/\[\]$/,lb=/\r?\n/g,Xb=/^(?:submit|button|image|reset|file)$/i,Yb=/^(?:input|select|textarea|keygen)/i;d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&Yb.test(this.nodeName)&&!Xb.test(a)&&(this.checked||!hb.test(a))}).map(function(a,b){var c=d(this).val();return null==c?null:
d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(lb,"\r\n")}}):{name:b.name,value:c.replace(lb,"\r\n")}}).get()}});d.param=function(a,b){var c,e=[],f=function(a,b){b=d.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(b===l&&(b=d.ajaxSettings&&d.ajaxSettings.traditional),d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Ea(c,a[c],b,f);return e.join("&").replace(Wb,"+")};d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var ga,U,Ma=d.now(),Na=/\?/,Zb=/#.*$/,mb=/([?&])_=[^&]*/,$b=/^(.*?):[ \t]*([^\r\n]*)$/gm,
ac=/^(?:GET|HEAD)$/,bc=/^\/\//,nb=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,ob=d.fn.load,pb={},Fa={},qb="*/".concat("*");try{U=Ab.href}catch(gc){U=y.createElement("a"),U.href="",U=U.href}ga=nb.exec(U.toLowerCase())||[];d.fn.load=function(a,b,c){if("string"!=typeof a&&ob)return ob.apply(this,arguments);var e,f,g,h=this,k=a.indexOf(" ");return 0<=k&&(e=a.slice(k),a=a.slice(0,k)),d.isFunction(b)?(c=b,b=l):b&&"object"==typeof b&&(f="POST"),0<h.length&&d.ajax({url:a,type:f,dataType:"html",data:b}).done(function(a){g=
arguments;h.html(e?d("<div>").append(d.parseHTML(a)).find(e):a)}).complete(c&&function(a,b){h.each(c,g||[a.responseText,b,a])}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:U,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(ga[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":qb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ga(Ga(a,d.ajaxSettings),b):Ga(d.ajaxSettings,a)},ajaxPrefilter:Ta(pb),ajaxTransport:Ta(Fa),ajax:function(a,
b){function c(a,b,c,h){var m,q,t,B,w=b;if(2!==y){y=2;k&&clearTimeout(k);e=l;g=h||"";u.readyState=0<a?4:0;h=200<=a&&300>a||304===a;if(c){t=n;for(var I=u,E,K,G,v,Z=t.contents,F=t.dataTypes;"*"===F[0];)F.shift(),E===l&&(E=t.mimeType||I.getResponseHeader("Content-Type"));if(E)for(K in Z)if(Z[K]&&Z[K].test(E)){F.unshift(K);break}if(F[0]in c)G=F[0];else{for(K in c){if(!F[0]||t.converters[K+" "+F[0]]){G=K;break}v||(v=K)}G=G||v}t=G?(G!==F[0]&&F.unshift(G),c[G]):l}var C;a:{c=n;E=t;K=u;G=h;var D,T,H;t={};I=
c.dataTypes.slice();if(I[1])for(D in c.converters)t[D.toLowerCase()]=c.converters[D];for(v=I.shift();v;)if(c.responseFields[v]&&(K[c.responseFields[v]]=E),!H&&G&&c.dataFilter&&(E=c.dataFilter(E,c.dataType)),H=v,v=I.shift())if("*"===v)v=H;else if("*"!==H&&H!==v){if(D=t[H+" "+v]||t["* "+v],!D)for(C in t)if(T=C.split(" "),T[1]===v&&(D=t[H+" "+T[0]]||t["* "+T[0]])){!0===D?D=t[C]:!0!==t[C]&&(v=T[0],I.unshift(T[1]));break}if(!0!==D)if(D&&c["throws"])E=D(E);else try{E=D(E)}catch(L){C={state:"parsererror",
error:D?L:"No conversion from "+H+" to "+v};break a}}C={state:"success",data:E}}t=C;h?(n.ifModified&&(B=u.getResponseHeader("Last-Modified"),B&&(d.lastModified[f]=B),B=u.getResponseHeader("etag"),B&&(d.etag[f]=B)),204===a||"HEAD"===n.type?w="nocontent":304===a?w="notmodified":(w=t.state,m=t.data,q=t.error,h=!q)):(q=w,(a||!w)&&(w="error",0>a&&(a=0)));u.status=a;u.statusText=(b||w)+"";h?r.resolveWith(z,[m,w,u]):r.rejectWith(z,[u,w,q]);u.statusCode(x);x=l;p&&s.trigger(h?"ajaxSuccess":"ajaxError",[u,
n,h?m:q]);Q.fireWith(z,[u,w]);p&&(s.trigger("ajaxComplete",[u,n]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=l);b=b||{};var e,f,g,h,k,m,p,q,n=d.ajaxSetup({},b),z=n.context||n,s=n.context&&(z.nodeType||z.jquery)?d(z):d.event,r=d.Deferred(),Q=d.Callbacks("once memory"),x=n.statusCode||{},B={},w={},y=0,I="canceled",u={readyState:0,getResponseHeader:function(a){var b;if(2===y){if(!h)for(h={};b=$b.exec(g);)h[b[1].toLowerCase()]=b[2];b=h[a.toLowerCase()]}return null==b?null:b},
getAllResponseHeaders:function(){return 2===y?g:null},setRequestHeader:function(a,b){var c=a.toLowerCase();return y||(a=w[c]=w[c]||a,B[a]=b),this},overrideMimeType:function(a){return y||(n.mimeType=a),this},statusCode:function(a){var b;if(a)if(2>y)for(b in a)x[b]=[x[b],a[b]];else u.always(a[u.status]);return this},abort:function(a){a=a||I;return e&&e.abort(a),c(0,a),this}};if(r.promise(u).complete=Q.add,u.success=u.done,u.error=u.fail,n.url=((a||n.url||U)+"").replace(Zb,"").replace(bc,ga[1]+"//"),
n.type=b.method||b.type||n.method||n.type,n.dataTypes=d.trim(n.dataType||"*").toLowerCase().match(R)||[""],null==n.crossDomain&&(m=nb.exec(n.url.toLowerCase()),n.crossDomain=!(!m||m[1]===ga[1]&&m[2]===ga[2]&&(m[3]||("http:"===m[1]?"80":"443"))===(ga[3]||("http:"===ga[1]?"80":"443")))),n.data&&n.processData&&"string"!=typeof n.data&&(n.data=d.param(n.data,n.traditional)),Ua(pb,n,b,u),2===y)return u;(p=n.global)&&0===d.active++&&d.event.trigger("ajaxStart");n.type=n.type.toUpperCase();n.hasContent=
!ac.test(n.type);f=n.url;n.hasContent||(n.data&&(f=n.url+=(Na.test(f)?"&":"?")+n.data,delete n.data),!1===n.cache&&(n.url=mb.test(f)?f.replace(mb,"$1_="+Ma++):f+(Na.test(f)?"&":"?")+"_="+Ma++));n.ifModified&&(d.lastModified[f]&&u.setRequestHeader("If-Modified-Since",d.lastModified[f]),d.etag[f]&&u.setRequestHeader("If-None-Match",d.etag[f]));(n.data&&n.hasContent&&!1!==n.contentType||b.contentType)&&u.setRequestHeader("Content-Type",n.contentType);u.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?
n.accepts[n.dataTypes[0]]+("*"!==n.dataTypes[0]?", "+qb+"; q=0.01":""):n.accepts["*"]);for(q in n.headers)u.setRequestHeader(q,n.headers[q]);if(n.beforeSend&&(!1===n.beforeSend.call(z,u,n)||2===y))return u.abort();I="abort";for(q in{success:1,error:1,complete:1})u[q](n[q]);if(e=Ua(Fa,n,b,u)){u.readyState=1;p&&s.trigger("ajaxSend",[u,n]);n.async&&0<n.timeout&&(k=setTimeout(function(){u.abort("timeout")},n.timeout));try{y=1,e.send(B,c)}catch(E){if(!(2>y))throw E;c(-1,E)}}else c(-1,"No Transport");return u},
getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,l,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){return d.isFunction(e)&&(g=g||f,f=e,e=l),d.ajax({url:a,type:b,dataType:g,data:e,success:f})}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",
function(a){a.cache===l&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({async:!0,charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});y.head.appendChild(b[0])},abort:function(){c&&c()}}}});var rb=[],Oa=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=rb.pop()||d.expando+"_"+Ma++;return this[a]=
!0,a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f,g,h=!1!==a.jsonp&&(Oa.test(a.url)?"url":"string"==typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Oa.test(a.data)&&"data");return h||"jsonp"===a.dataTypes[0]?(e=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Oa,"$1"+e):!1!==a.jsonp&&(a.url+=(Na.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){return g||d.error(e+" was not called"),
g[0]},a.dataTypes[0]="json",f=r[e],r[e]=function(){g=arguments},c.always(function(){r[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,rb.push(e));g&&d.isFunction(f)&&f(g[0]);g=f=l}),"script"):l});d.ajaxSettings.xhr=function(){try{return new XMLHttpRequest}catch(a){}};var pa=d.ajaxSettings.xhr(),cc={0:200,1223:204},dc=0,qa={};r.ActiveXObject&&d(r).on("unload",function(){for(var a in qa)qa[a]();qa=l});d.support.cors=!!pa&&"withCredentials"in pa;d.support.ajax=pa=!!pa;d.ajaxTransport(function(a){var b;return d.support.cors||
pa&&!a.crossDomain?{send:function(c,d){var f,g,h=a.xhr();if(h.open(a.type,a.url,a.async,a.username,a.password),a.xhrFields)for(f in a.xhrFields)h[f]=a.xhrFields[f];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||c["X-Requested-With"]||(c["X-Requested-With"]="XMLHttpRequest");for(f in c)h.setRequestHeader(f,c[f]);b=function(a){return function(){b&&(delete qa[g],b=h.onload=h.onerror=null,"abort"===a?h.abort():"error"===a?d(h.status||404,h.statusText):d(cc[h.status]||h.status,
h.statusText,"string"==typeof h.responseText?{text:h.responseText}:l,h.getAllResponseHeaders()))}};h.onload=b();h.onerror=b("error");b=qa[g=dc++]=b("abort");h.send(a.hasContent&&a.data||null)},abort:function(){b&&b()}}:l});var W,Ba,ec=/^(?:toggle|show|hide)$/,sb=RegExp("^(?:([+-])=|)("+ya+")([a-z%]*)$","i"),fc=/queueHooks$/,da=[function(a,b,c){var e,f,g,h,k,m=this,p={},q=a.style,n=a.nodeType&&I(a),s=x.get(a,"fxshow");c.queue||(h=d._queueHooks(a,"fx"),null==h.unqueued&&(h.unqueued=0,k=h.empty.fire,
h.empty.fire=function(){h.unqueued||k()}),h.unqueued++,m.always(function(){m.always(function(){h.unqueued--;d.queue(a,"fx").length||h.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(c.overflow=[q.overflow,q.overflowX,q.overflowY],"inline"===d.css(a,"display")&&"none"===d.css(a,"float")&&(q.display="inline-block"));c.overflow&&(q.overflow="hidden",m.always(function(){q.overflow=c.overflow[0];q.overflowX=c.overflow[1];q.overflowY=c.overflow[2]}));for(e in b)if(f=b[e],ec.exec(f)){if(delete b[e],
g=g||"toggle"===f,f===(n?"hide":"show")){if("show"!==f||!s||s[e]===l)continue;n=!0}p[e]=s&&s[e]||d.style(a,e)}if(!d.isEmptyObject(p))for(e in s?"hidden"in s&&(n=s.hidden):s=x.access(a,"fxshow",{}),g&&(s.hidden=!n),n?d(a).show():m.done(function(){d(a).hide()}),m.done(function(){var b;x.remove(a,"fxshow");for(b in p)d.style(a,b,p[b])}),p)b=Wa(n?s[e]:0,e,m),e in s||(s[e]=b.start,n&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],ca={"*":[function(a,b){var c=this.createTween(a,b),e=c.cur(),f=
sb.exec(b),g=f&&f[3]||(d.cssNumber[a]?"":"px"),h=(d.cssNumber[a]||"px"!==g&&+e)&&sb.exec(d.css(c.elem,a)),k=1,m=20;if(h&&h[3]!==g){g=g||h[3];f=f||[];h=+e||1;do k=k||".5",h/=k,d.style(c.elem,a,h+g);while(k!==(k=c.cur()/e)&&1!==k&&--m)}return f&&(h=c.start=+h||+e||0,c.unit=g,c.end=f[1]?h+(f[1]+1)*f[2]:+f[2]),c}]};d.Animation=d.extend(Xa,{tweener:function(a,b){d.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var c,e=0,f=a.length;f>e;e++)c=a[e],ca[c]=ca[c]||[],ca[c].unshift(b)},prefilter:function(a,b){b?
da.unshift(a):da.push(a)}});d.Tween=O;O.prototype={constructor:O,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=O.propHooks[this.prop];return a&&a.get?a.get(this):O.propHooks._default.get(this)},run:function(a){var b,c=O.propHooks[this.prop];return this.pos=b=this.options.duration?d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):
a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):O.propHooks._default.set(this),this}};O.prototype.init.prototype=O.prototype;O.propHooks={_default:{get:function(a){var b;return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(b=d.css(a.elem,a.prop,""),b&&"auto"!==b?b:0):a.elem[a.prop]},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):a.elem.style&&(null!=a.elem.style[d.cssProps[a.prop]]||d.cssHooks[a.prop])?
d.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};O.propHooks.scrollTop=O.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"==typeof a?c.apply(this,arguments):this.animate(ha(b,!0),a,d,g)}});d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(I).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=
d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=Xa(this,d.extend({},a),g);(f||x.get(this,"finish"))&&b.stop(!0)};return b.finish=b,f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};return"string"!=typeof a&&(c=b,b=a,a=l),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=d.timers,k=x.get(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&fc.test(g)&&e(k[g]);for(g=
h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b,c=x.get(this),e=c[a+"queue"];b=c[a+"queueHooks"];var f=d.timers,g=e?e.length:0;c.finish=!0;d.queue(this,a,[]);b&&b.stop&&b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;g>b;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete c.finish})}});
d.each({slideDown:ha("show"),slideUp:ha("hide"),slideToggle:ha("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.speed=function(a,b,c){var e=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};return e.duration=d.fx.off?0:"number"==typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default,
(null==e.queue||!0===e.queue)&&(e.queue="fx"),e.old=e.complete,e.complete=function(){d.isFunction(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)},e};d.easing={linear:function(a){return a},swing:function(a){return 0.5-Math.cos(a*Math.PI)/2}};d.timers=[];d.fx=O.prototype.init;d.fx.tick=function(){var a,b=d.timers,c=0;for(W=d.now();b.length>c;c++)a=b[c],a()||b[c]!==a||b.splice(c--,1);b.length||d.fx.stop();W=l};d.fx.timer=function(a){a()&&d.timers.push(a)&&d.fx.start()};d.fx.interval=13;d.fx.start=
function(){Ba||(Ba=setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){clearInterval(Ba);Ba=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fx.step={};d.expr&&d.expr.filters&&(d.expr.filters.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length});d.fn.offset=function(a){if(arguments.length)return a===l?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b,c,e=this[0],f={top:0,left:0},g=e&&e.ownerDocument;if(g)return b=g.documentElement,d.contains(b,
e)?(typeof e.getBoundingClientRect!==ta&&(f=e.getBoundingClientRect()),c=d.isWindow(g)?g:9===g.nodeType&&g.defaultView,{top:f.top+c.pageYOffset-b.clientTop,left:f.left+c.pageXOffset-b.clientLeft}):f};d.offset={setOffset:function(a,b,c){var e,f,g,h,k,m,l=d.css(a,"position"),p=d(a),n={};"static"===l&&(a.style.position="relative");k=p.offset();g=d.css(a,"top");m=d.css(a,"left");("absolute"===l||"fixed"===l)&&-1<(g+m).indexOf("auto")?(e=p.position(),h=e.top,f=e.left):(h=parseFloat(g)||0,f=parseFloat(m)||
0);d.isFunction(b)&&(b=b.call(a,c,k));null!=b.top&&(n.top=b.top-k.top+h);null!=b.left&&(n.left=b.left-k.left+f);"using"in b?b.using.call(a,n):p.css(n)}};d.fn.extend({position:function(){if(this[0]){var a,b,c=this[0],e={top:0,left:0};return"fixed"===d.css(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),d.nodeName(a[0],"html")||(e=a.offset()),e.top+=d.css(a[0],"borderTopWidth",!0),e.left+=d.css(a[0],"borderLeftWidth",!0)),{top:b.top-e.top-d.css(c,"marginTop",!0),left:b.left-
e.left-d.css(c,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||Za;a&&!d.nodeName(a,"html")&&"static"===d.css(a,"position");)a=a.offsetParent;return a||Za})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(e){return d.access(this,function(a,e,h){var k=d.isWindow(a)?a:9===a.nodeType&&a.defaultView;return h===l?k?k[b]:a[e]:(k?k.scrollTo(c?r.pageXOffset:h,c?h:r.pageYOffset):a[e]=h,l)},
a,e,arguments.length,null)}});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(e,g){var h=arguments.length&&(c||"boolean"!=typeof e),k=c||(!0===e||!0===g?"margin":"border");return d.access(this,function(b,c,e){var f;return d.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):e===l?d.css(b,
c,k):d.style(b,c,e,k)},b,h?e:l,h,null)}})});d.fn.size=function(){return this.length};d.fn.andSelf=d.fn.addBack;"object"==typeof module&&module&&"object"==typeof module.exports?module.exports=d:"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});"object"==typeof r&&"object"==typeof r.document&&(r.jQuery=r.$=d)})(window);(function(r){r.extend({bullet:function(l,F){function V(){var s=0,r;for(r in E){if(w==s){var p=E[r]();if(p)return s=new p.transport(l),s.heart=p.heart,s;w++}s++}return!1}var C=0,v=1,L=2,N=3,P=function(s){if(this.readyState!=C&&this.readyState!=v)return!1;var E=l.replace("ws:","http:").replace("wss:","https:"),p=this;r.ajax({async:!1,cache:!1,type:"POST",url:E,data:s,dataType:"text",contentType:"application/x-www-form-urlencoded; charset=utf-8",headers:{"X-Socket-Transport":"xhrPolling"},success:function(l){if(l&&
0!==l.length)p.onmessage({data:l})}});return!0},E={websocket:function(){var l=null;if(void 0!==F&&F.disableWebSocket)return!1;window.WebSocket&&(l=window.WebSocket);window.MozWebSocket&&-1==navigator.userAgent.indexOf("Firefox/6.0")&&(l=window.MozWebSocket);return l?{heart:!0,transport:l}:null},eventsource:function(){if(void 0!==F&&F.disableEventSource||!window.EventSource)return!1;var s=l.replace("ws:","http:").replace("wss:","https:"),r=new window.EventSource(s);r.onopen=function(){p.readyState=
v;p.onopen()};r.onmessage=function(l){p.onmessage(l)};r.onerror=function(){r.close();r=void 0;p.onerror()};var p={readyState:C,send:P,close:function(){p.readyState=N;r.close();r=void 0;p.onclose()}};return{heart:!1,transport:function(){return p}}},xhrPolling:function(){function s(){var p=l.replace("ws:","http:").replace("wss:","https:");w=r.ajax({type:"GET",cache:!1,url:p,dataType:"text",data:{},headers:{"X-Socket-Transport":"xhrPolling"},success:function(l){w=null;q.readyState==C&&(q.readyState=
v,q.onopen(q));if(l&&0!==l.length)q.onmessage({data:l});q.readyState==v&&E()},error:function(l){q.onerror()}})}function E(){p=setTimeout(function(){s()},100)}if(void 0!==F&&F.disableXHRPolling)return!1;var p,w=null,q={readyState:C,send:P,close:function(){this.readyState=N;w&&(w.abort(),w=null);clearTimeout(p);q.onclose()},onopen:function(){},onmessage:function(){},onerror:function(){},onclose:function(){}};E();return{heart:!1,transport:function(){return q}}}},w=0,B=new function(){function s(){r=!1;
p=C;G=V();if(!G)return q=F,w=0,B.ondisconnect(),setTimeout(function(){s()},I),!1;G.onopen=function(){q=F;G.heart&&(E=setInterval(function(){B.onheartbeat()},2E4));p!=v&&(p=v,B.onopen())};G.onclose=function(){r||p==N||(G=null,clearInterval(E),p==L?(p=N,G=!1,B.onclose()):(p==C&&w++,q*=2,q>I&&(q=I),r=!0,setTimeout(function(){s()},q)))};G.onerror=G.onclose;G.onmessage=function(l){B.onmessage(l)}}var r=!0,p=N,E,q=80,F=80,I=1E4,G;s();this.onopen=function(){};this.onmessage=function(){};this.ondisconnect=
function(){};this.onclose=function(){};this.onheartbeat=function(){};this.setURL=function(p){l=p};this.send=function(l){return G?G.send(l):!1};this.close=function(){p=L;G&&G.close()}};return B}})})(jQuery);(function(){function r(l){function r(l,w){var v=Math.floor(Math.random()*Math.pow(2,32)),s=JSON.stringify({type:l,data:w,ref:v});P.send(s);return v}function V(l,w,B,s,C){var p=this;p.messages=[];p.users=[];(function(l,q,s){function w(){B--;B||(p.messages=K,p.users=C,s(C,K))}var E=r("join",l);l=r("messages_before",{room:l,timestamp:Date.now(),limit:q});var B=2,C=null,K=null;v[E]=function(l){C=l;w()};v[l]=function(l){K=l;w()}})(l,w,B);this.send=function(s,q){var w=r("message",{room:l,content:s});v[w]=
function(l){p.messages.push({username:N,content:s,timestamp:l});q(l)}};this.load=function(s,q){var w=r("messages_before",{room:l,timestamp:p.messages[0].timestamp,limit:s});v[w]=function(l){p.messages=p.messages.concat(l);q(l,p.messages)}};this.reconnect=function(s){var q=r("join",l);v[q]=function(l){for(var q=p.users,s=q.length;s--;){var r=q[s];if(-1===l.indexOf(r))p.onUser("leave",r)}for(s=l.length;s--;)if(r=l[s],-1===q.indexOf(l[s]))p.onUser("join",r)};p.messages.length&&(s=r("messages_between",
{room:l,startTimestamp:p.messages[p.messages.length-1].timestamp,endTimestamp:s}),v[s]=function(l){p.messages=p.messages.concat(l);for(var q=0;q<l.length;q++){var s=l[q];p.onMessage(s.username,s.content,s.timestamp)}})};this.onUser=function(l,q){switch(l){case "join":p.users.push(q);break;case "leave":for(var r=p.users.length;r--;)p.users[r]===q&&(p.users.splice(r,1),r=0);break;default:throw"invalid action";}s(l,q,p.users)};this.onMessage=function(l,q,s){p.messages.push({username:l,content:q,timestamp:s});
C(l,q,s,p.messages)}}var C=this,v={},L={},N=null,P=$.bullet("ws://"+window.document.location.host+"/bullet");(function(){var r=!1;P.onopen=function(){if(r)try{C.username(N,function(l){if(!l)throw"username not available";});var w=Date.now(),v;for(v in L)L[v].reconnect(w)}catch(s){console.error("eChat: Unable to reconnect because or error",s)}else l(),r=!0}})();P.onmessage=function(l){try{var r=JSON.parse(l.data),B=r.data,s=r.ref;switch(r.type){case "register_res":v[s](B);v[s]=null;break;case "users":v[s](B);
v[s]=null;break;case "messages":v[s](B);v[s]=null;break;case "message_timestamp":v[s](B);v[s]=null;break;case "user":L[B.room].onUser(B.action,B.username);break;case "message":L[B.room].onMessage(B.message.username,B.message.content,B.message.timestamp);break;default:throw"invalid type";}}catch(C){console.error("eChat: Unable to handle message",l.data,"because of error",C)}};this.username=function(l,w){var B=r("register",l);v[B]=function(s){s&&(N=l);w(s)}};this.join=function(l,r,v,s,C){L[l]=new V(l,
r,v,s,C)};this.room=function(l){return L[l]};this.leave=function(l){r("leave",l);L[l]=null}}window.echat=function(l){return new r(l)}})();
